# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3b4f5d533916fbb99230523d27f4fc60395374248df21c79e3aee9d3e94da6e6b71b701fb2413ae36790834fc851953a1e20d9dad210cbb10957c7f103c231

test:
  secret_key_base: 647e8343ca90817553450f55cb1de66032f9fffa0774feba1351a76db14c0a613b44e7137a49d3ca91572525ae29247dbae744a1029d9db3e666964e4a9a37d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
